# Generated by Django 5.1.8 on 2025-04-15 10:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('Classic Casual', 'Classic Casual'), ('Sporty (Athleisure)', 'Sporty (Athleisure)'), ('Streetwear', 'Streetwear'), ('Bohemian (Boho)', 'Bohemian (Boho)'), ('Preppy', 'Preppy'), ('Hipster', 'Hipster'), ('Grunge', 'Grunge'), ('Minimalist', 'Minimalist'), ('Y2K Fashion', 'Y2K Fashion'), ('Soft Girl', 'Soft Girl'), ('VSCO Girl', 'VSCO Girl'), ('Cottagecore', 'Cottagecore'), ('E-Girl', 'E-Girl'), ('Skater', 'Skater'), ('Dark Academia', 'Dark Academia'), ('Light Academia', 'Light Academia'), ('Indie', 'Indie'), ('Business Casual', 'Business Casual'), ('Business Professional', 'Business Professional'), ('Smart Casual', 'Smart Casual'), ('Power Dressing', 'Power Dressing'), ('Punk', 'Punk'), ('Gothic', 'Gothic'), ('Cyberpunk', 'Cyberpunk'), ('Rockstar Chic', 'Rockstar Chic'), ('Steampunk', 'Steampunk'), ('Emo', 'Emo'), ('Gyaru', 'Gyaru'), ('Vintage', 'Vintage'), ('Retro', 'Retro'), ('Kawaii', 'Kawaii'), ('Harajuku', 'Harajuku'), ('Lolita', 'Lolita'), ('K-Pop Fashion', 'K-Pop Fashion'), ('Hippie', 'Hippie'), ('Winter Fashion', 'Winter Fashion'), ('Summer Fashion', 'Summer Fashion'), ('Resort Wear', 'Resort Wear'), ('Workwear (Utility Fashion)', 'Workwear (Utility Fashion)'), ('Avant-Garde', 'Avant-Garde'), ('Haute Couture', 'Haute Couture'), ('Luxury Chic', 'Luxury Chic'), ('Sci-Fi/Fantasy Fashion', 'Sci-Fi/Fantasy Fashion'), ('Rave/Festival Fashion', 'Rave/Festival Fashion'), ('Normcore', 'Normcore')], max_length=50)),
                ('image', models.ImageField(blank=True, default='../default_post_umaui6', upload_to='images/')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
