# Generated by Django 5.1.8 on 2025-04-16 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='../default_avatar_aiks6l', upload_to='images/'),
        ),
    ]
